name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup System
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.5
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
        cd /opt
        sudo wget http://www.imagemagick.org/download/ImageMagick.tar.gz
        sudo tar xvzf ImageMagick.tar.gz
        cd ImageMagick-7.0.8-2
        sudo touch configure
        sudo ./configure
        sudo make
        sudo make install
        sudo ldconfig /usr/local/lib
        sudo make check
        convert --version
    - name: Install Chromedriver
      run: |
        # Install Chromedriver
        CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        sudo wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver
    - name: Install dependencies
      run: bundle install
      env:
        RAILS_ENV: test
    - name: Run tests
      run: |
        yarn install --check-files
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rspec
      env:
        RAILS_ENV: test
